insert into GL_TCLIENTES(CLI_CEDULA,CLI_TIPODOCUMENTO,CLI_NOMBRES,CLI_CIUDAD_ID,CLI_CORREO,CLI_CELULAR,CLI_ESTADO,CLI_DIRECCION) 
values('79848026',1,'guiovanny caro',1,'guiovanny.caro@outlook.com','3160405672','1','calle falsa 123');
commit;



insert into GL_TUSUARIOS(USU_NOMBRES,USU_DIRECCION,USU_TELEFONO,USU_CORREO,USU_NUMDOCUMENTO,USU_PASSWORD,USU_TDOC_ID,USU_ROL_ID,USU_ESTADO) 
values('guiovanny caro','caLLE FALSA 123','3160405672','guiovanny.caro@outlook.com','79848026','Admin123','1','1','1');
commit;



insert into GL_TENVIO(ENV_CLIE_ID,ENV_TELEFONO,ENV_BOD_ID,ENV_FECHA_ENTREGA,ENV_FECHA_ENVIO,ENV_ORIG_CIU_ID,ENV_DEST_CIU_ID,ENV_ESTADO) 
values('1','3160404572','1','11/02/2024','10/01/2024','1','2','1');
commit;



insert into GL_TPRODUCTOS(PRO_NOMBRES,PRO_DESCRIPCION,PRO_OBSERVACION,PROD_VALOR,PROD_CANTIDAD,PRO_ESTADO) 
values('Cama','trasteo','embalada desde armenia','20000000','1','1');
commit;



