CREATE SEQUENCE GL_SCLIENTES
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SBODEGA
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SENVIO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SDETALLEENVIO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SDETALLEENVIOTEMP
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SZONAS
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_SUSUARIOS
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_STIPOPRODUCTO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE GL_STIPODOCUMENTO
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE GL_STIPOBODEGA
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE GL_SROLES
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE GL_SPRODUCTOS
START WITH
    1 INCREMENT BY 1;